/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 03 17:27:40 GMT 2025
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Stack_ESTest extends Stack_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Stack stack0 = new Stack(1127);
      stack0.push(1);
      int int0 = stack0.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Stack stack0 = new Stack(2560);
      stack0.push(0);
      int int0 = stack0.pop();
      assertEquals(0, stack0.size());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Stack stack0 = new Stack(10);
      stack0.push(10);
      int int0 = stack0.pop();
      assertEquals(0, stack0.size());
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Stack stack0 = new Stack(30);
      stack0.push(0);
      int int0 = stack0.peek();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Stack stack0 = new Stack(1127);
      stack0.push(1);
      int int0 = stack0.peek();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Stack stack0 = null;
      try {
        stack0 = new Stack((-5819));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -5819
         //
         verifyException("Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Stack stack0 = new Stack(1127);
      assertTrue(stack0.isEmpty());
      
      stack0.push(1);
      boolean boolean0 = stack0.isEmpty();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Stack stack0 = new Stack(1);
      stack0.push((-174));
      int int0 = stack0.peek();
      assertTrue(stack0.isFull());
      assertEquals((-174), int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Stack stack0 = new Stack(1);
      int int0 = stack0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Stack stack0 = new Stack(0);
      boolean boolean0 = stack0.isFull();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Stack stack0 = new Stack(1);
      stack0.push((-174));
      assertTrue(stack0.isFull());
      
      stack0.pop();
      boolean boolean0 = stack0.isFull();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Stack stack0 = new Stack(1127);
      boolean boolean0 = stack0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Stack stack0 = new Stack(2097);
      // Undeclared exception!
      try { 
        stack0.peek();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Stack is empty
         //
         verifyException("Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Stack stack0 = new Stack(0);
      // Undeclared exception!
      try { 
        stack0.pop();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Stack is empty
         //
         verifyException("Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Stack stack0 = new Stack(0);
      // Undeclared exception!
      try { 
        stack0.push(0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Stack is full
         //
         verifyException("Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String[] stringArray0 = new String[9];
      Stack.main(stringArray0);
      assertEquals(9, stringArray0.length);
  }
}
